# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.14.0
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/New\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/New\\Library\\include']
blas_opt_info:
    libra

#### 3. Create a null vector of size 10

In [7]:
c=np.zeros(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [12]:
a=c.size
b=c.itemsize
print(a*b ,end=' ')
print("bytes")

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [15]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [17]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [20]:
arr=np.arange(10,50,3)
print(arr)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


#### 8.  Reverse a vector (first element becomes last)

In [21]:
print(arr[::-1])

[49 46 43 40 37 34 31 28 25 22 19 16 13 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
arr=np.random.randint(0,9,(3,3))
arr

array([[3, 1, 3],
       [0, 4, 5],
       [8, 0, 4]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [24]:
a=np.array([1,2,0,0,4,0])
x=np.nonzero(a)
x

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [27]:
np.random.random((3,3,3))

array([[[0.53181299, 0.33302819, 0.08222182],
        [0.95999699, 0.10926415, 0.80231899],
        [0.6219037 , 0.5077128 , 0.55173084]],

       [[0.41875134, 0.39760483, 0.76352597],
        [0.57775324, 0.22217829, 0.23178341],
        [0.97635959, 0.69436473, 0.88257068]],

       [[0.86082126, 0.36239932, 0.89651556],
        [0.27244509, 0.01501548, 0.05067516],
        [0.72575155, 0.40209426, 0.41366555]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
arr=np.random.random((10,10))
a=np.max(arr)
b=np.min(arr)
print(a,b,sep='\n')

0.9940257964762608
0.0184669125446979


#### 14. Create a random vector of size 30 and find the mean value

In [36]:
arr=np.random.random((30))
t=np.mean(arr)
t

0.49871992253864617

#### 15. Create a 2d array with 1 on the border and 0 inside

In [47]:
p= np.ones((5,5))
p[1:-1,1:-1]=0
p

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [48]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [49]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [53]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [54]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [55]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)